### PR TITLE
Add submitted timestamp header

### PR DESCRIPTION
**Pull request by CharlesGarth**
Add a header to POST request containing the submission time of a message.

Key: "submitted"
Value: long (UTC epoch in milliseconds)

### CODE REVIEW

**Review by charlierobson — APPROVED** [review]

**Comment by charlierobson** [comment]
👍

**Review by ejarlewski — APPROVED** [review]
👍

**Review by ejarlewski — CHANGES_REQUESTED** [review]
I think this maybe should use UTC

**Review by ejarlewski — COMMENTED** [review]
👍

**Pull request merged**
